### ISSUE TITLE
Code reuse permission?

### ISSUE THREAD

**Issue by Nindaleth** [jesusferm/Nautilus-43-BackSpace#1]
Hi, I'd love to create my own extension which would be based on your work, and provide more hotkeys in it. There's no licence listed in this repo, though, and I don't think I'm allowed to do that without permission. Would it be alright if I reuse your code and link your repo in the source?

**Comment by jesusferm** [comment]
> 
Hello.

Yes you are allowed to use the code and apply it for what is needed. You publish in content when you finish and put to use the functionalities you develop.

Thank you.

**Comment by Nindaleth** [comment]
Thank you!
